### ISSUE TITLE
Feature request - allow to show alerts without of "await"

### ISSUE THREAD

**Issue by Gargo** [Jaesung-Jung/SwiftyAlert#1]
In many cases you just show alert and don't care about its result (and don't need to wait for some result)

**Comment by Jaesung-Jung** [comment]
@Gargo 

Thank you for requesting this feature. Sorry for the delay in responding, I've been busy at work.
I have released version 1.1.0 added `present` alerts without `await`.

The method is to use `present(from:)` without await.
However, this method is only available for `Alert<Void>`.

Check the [example code](https://github.com/Jaesung-Jung/SwiftyAlert/blob/191777179ce9f4968119092b998ccff924b75e41/Example/SwiftyAlertExample/ViewController.swift#L82-L91) if you needed.
