### ISSUE TITLE
UIPopoverPresentationController not available in tvOS

### ISSUE THREAD

**Issue by gabors** [Jaesung-Jung/SwiftyAlert#2]
Thanks for this package @Jaesung-Jung 
Unfortunately unable to build on tvOS because of the UIPopoverPresentationController not available

**Comment by Jaesung-Jung** [comment]
@gabors Oh this is my mistake, I'll fix it quickly and deploy it, sorry for the delay.

**Comment by gabors** [comment]
Thanks @Jaesung-Jung !

**Comment by Jaesung-Jung** [comment]
@gabors 
Released `1.1.1` with a build error fix on tvOS.
Removed [popoverPresentation(_:)](https://github.com/Jaesung-Jung/SwiftyAlert/blob/2f5b4943005d3962f009d4ceb413e126d2cb5480/Sources/SwiftyAlert/Alert.swift#L107C6-L107C6) interface on tvOS.
