### ISSUE TITLE
Can't use confirm alert in synchronous methods

### ISSUE THREAD

**Issue by yanshiyason** [Jaesung-Jung/SwiftyAlert#3]
Hi there, thank you very much for this library, it has served me well these past few months!

I had this code in an `async` function which worked well:

```
 let alert = Alert(style: .alert)
      .title(data.title)
      .message(data.message)
      .action(.cancel(data.noLabel))
      .action(.destructive(data.yesLabel))

switch alert.present(from: vc!) {
      case .done:
        return true
      case .cancel:
        return false
      }
```

But now, I want to reuse the same code in a non-async function, and I can't seem to get the ".done" or ".cancel" value back from the "present" call.

```
// Compile error: Value of tuple type '()' has no member 'done'
switch alert.present(from: vc!) {
      case .done:
        // do something
      case .cancel:
        // do something else
      }
```

Do you have any idea how I can achieve this?

**Comment by yanshiyason** [comment]
I was able to get it to work with the following code 👌 

```
private func mySyncMethod() {
  // If I try to access my view controller inside the Task below, I get warnings about UI code running in background thread
  // so I first access that here.
  let vc = Application.myVc
  
  // Then prepare a function with a callback to run the async code
  func awaitedResult(callback: @escaping (Bool) -> Void) {
    Task {
      // This presentAlert function is what calls alert.present(from:)
      let result = await presentAlert(from: vc, data: data)
      DispatchQueue.main.async {
        callback(result)
      }
    }
  }
  
  awaitedResult { result in
    if result {
      // User pressed "yes"
    } else {
      // User pressed "no"
    }
  }
}
```

**Comment by Jaesung-Jung** [comment]
@yanshiyason 
hello.

Alerts use the `async / await` model. Because the user must select `done` or `cancel`, to receive the result.
The code you posted is a synchronous method, so the return value is Void type. (Like tuple type '()')

If you need to receive the result, you should use the async / await model.
Only alerts that don't require a result value can use synchronous calls.

Thanks.
